project:
  type: website
  output-dir: _site
  render:
    - "protvino-2026/index.qmd"

format:
  revealjs:
    theme: black
    css: styles/reveal-dark.css
    logo: shared/figures/dvnlogo.png
    embed-resources: true
    slide-number: true
    slide-level: 2
    toc: false
    width: 1280
    height: 720
    margin: 0.06
    transition: fade
    center: false
    incremental: false
    chalkboard: false
    preview-links: false

execute:
  echo: false
  warning: false
  message: false
