name: Build talks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: make pdf
      - uses: actions/upload-artifact@v4
        with:
          name: protvino-2026-talk
          path: |
            _site/**
            dist/*.pdf
