name: Publish site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: NeutrinoHit/NeutrinoHit.github.io/.github/workflows/publish-reusable.yml@main
